version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm --prefix frontend install
  build:
    commands:
      - npm --prefix frontend run build
artifacts:
  files:
    - '**/*'
  base-directory: frontend
