version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - cd backend
  build:
    commands:
      - cd backend && pip install -r requirements.txt
artifacts:
  files:
    - '**/*'
  base-directory: backend
